"""Fan-in extraction and hierarchical slicing over generated SystemVerilog.

These use synthetic firtool-shaped input rather than a real build, so they run
without a 20-minute elaboration and still pin the grammar that matters.
"""
from pathlib import Path

import pytest

from waveql.ingest.netlist import (HierNetlist, identifiers, parse_instances,
                                   parse_module, parse_ports)

CHILD = """\
// Generated by CIRCT firtool-1.75.0
module Child(\t// @[a.scala:1:7]
  input         clock,\t// @[a.scala:1:7]
  input         io_in,\t// @[a.scala:2:14]
  output        io_out\t// @[a.scala:2:14]
);
  wire      inner = io_in & 1'h1;\t// @[a.scala:10:20]
  assign io_out = inner;\t// @[a.scala:11:9]
endmodule
"""

PARENT = """\
module Parent(\t// @[b.scala:1:7]
  input         clock,
  input         src
);
  wire  _child_io_out;\t// @[b.scala:5:20]
  reg   held;\t// @[b.scala:6:24]
  wire  gate = src | held;\t// @[b.scala:7:18]
  always @(posedge clock) begin\t// @[b.scala:9:7]
    if (gate) begin\t// @[b.scala:10:11]
      held <= _child_io_out;\t// @[b.scala:11:13]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    initial begin
      held = _RANDOM[3'h1];
    end
  `endif // ENABLE_INITIAL_REG_
  Child child (\t// @[b.scala:20:22]
    .clock  (clock),
    .io_in  (gate),\t// @[b.scala:21:9]
    .io_out (_child_io_out)\t// @[b.scala:22:9]
  );
endmodule
"""


@pytest.fixture
def gen(tmp_path: Path) -> Path:
    coll = tmp_path / "gen-collateral"
    coll.mkdir()
    (coll / "Child.sv").write_text(CHILD)
    (coll / "Parent.sv").write_text(PARENT)
    return tmp_path


def test_identifiers_skips_literals_and_keywords():
    assert identifiers("a & 2'h3 | b") == ["a", "b"]
    assert identifiers("{x, y[3:0]}") == ["x", "y"]
    # A sized literal's radix letter must not be mistaken for a signal.
    assert "h" not in identifiers("32'hDEAD")


def test_wire_and_assign_fanin(gen: Path):
    d = parse_module(gen / "gen-collateral" / "Child.sv")
    assert d["inner"].data == ("io_in",)
    assert str(d["inner"].refs[0]) == "a.scala:10:20"
    assert d["io_out"].kind == "assign"
    assert d["io_out"].data == ("inner",)


def test_register_records_enable_as_control(gen: Path):
    """A stuck register is usually not written at all, so the enable is the
    interesting dependence -- it must not be collapsed into the data fan-in."""
    d = parse_module(gen / "gen-collateral" / "Parent.sv")
    assert d["held"].data == ("_child_io_out",)
    assert "gate" in d["held"].control


def test_randomization_block_is_not_dataflow(gen: Path):
    """`ifdef ENABLE_INITIAL_REG_ is simulation scaffolding; left in, every
    register gains a fan-in on _RANDOM that does not exist in hardware."""
    d = parse_module(gen / "gen-collateral" / "Parent.sv")
    assert "_RANDOM" not in d["held"].fanin


def test_ports_and_instances(gen: Path):
    assert parse_ports(gen / "gen-collateral" / "Child.sv") == {
        "clock": "input", "io_in": "input", "io_out": "output"}
    inst = parse_instances(gen / "gen-collateral" / "Parent.sv")
    assert [i.name for i in inst] == ["child"]
    assert inst[0].module == "Child"
    assert inst[0].conns["io_out"] == "_child_io_out"


def test_slice_crosses_module_boundaries_both_ways(gen: Path):
    """The defect is rarely in the module where the symptom appears, so a slice
    confined to one module cannot reach it."""
    nl = HierNetlist(gen, {"top": "Parent", "top.child": "Child"})
    steps = nl.slice("top", "held", max_depth=6)
    got = {(s.signal, s.via) for s in steps}
    assert ("gate", "control") in got                 # enable, same module
    assert ("_child_io_out", "data") in got           # child output, same module
    assert ("io_out", "port-down") in got             # descended into Child
    assert ("inner", "data") in got                   # inside Child
    assert ("io_in", "data") in got
    assert ("gate", "port-up") in got or ("gate", "control") in got
    assert any(s.module == "Child" for s in steps)


def test_slice_keep_set_restricts_to_recorded_signals(gen: Path):
    """Intersecting with the waveform is what keeps a slice from covering logic
    the run never exercised."""
    nl = HierNetlist(gen, {"top": "Parent", "top.child": "Child"})
    steps = nl.slice("top", "held", max_depth=6, keep={"top._child_io_out"})
    assert {s.signal for s in steps if s.via in ("data", "control")} == {"_child_io_out"}
